In [1]:
print('Hello World')

Hello World


ALT+ENTER运行代码
Esc+m & Esc+a切换输入方式

# Python基础语法
## 运算
默认是浮点运算   
加 +  
减 -  
乘 *  
除 /  
取余 %  
指数 ** （平方） 
复利运算 本金*利息 ** 期数  
 
复利计算公式是计算前一期利息再生利息的问题，计入本金重复计息，即“利生利”“利滚利”。它的计算方法主要分为2种：一种是一次支付复利计算；另一种是等额多次支付复利计算

In [7]:
a = 15
b = 4
c = 1.1
print(a + b) 
print(a - b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a*c**b)

19
11
60
3.75
3
50625
21.961500000000004


## 数据类型
```type(a)```可以查看a的变量类型  
数据类型的强制转换  eg：```int(float x)```

In [15]:
a=2;b=0.13;c = True;d = "Sw"
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


## List列表
种复合的数据类型
列表切片

连续显示一串列表内容
```list_name[start:end]```
列表项的添加：```List[0:2] = [aa,dd]```
列表项的删减：```del(List[x])```

In [23]:
Student = ["Sw","男",20,2321]
print(Student)
print(type(Student))

['Sw', '男', 20, 2321]
<class 'list'>


In [24]:
Student[1]

'男'

In [26]:
Student = [['Name',"Sw"],['Sex',"男"],['age',20],['Num',2321]]

Student

[['Name', 'Sw'], ['Sex', '男'], ['age', 20], ['Num', 2321]]

In [29]:
Student[0][0]

'Name'

In [31]:
Student[-1][-1] #-1指向列表尾

2321

In [33]:
Student[2:4]

[['age', 20], ['Num', 2321]]

In [43]:
round(2.3,1)

2.3

In [44]:
?round

In [58]:
Student.index()

TypeError: index() takes at least 1 argument (0 given)

In [46]:
print(len(Student))

4


In [47]:
Student

[['Name', 'Sw'], ['Sex', '男'], ['age', 20], ['Num', 2321]]

In [49]:
num=[12,45,6,89,6776,87,0.8,0]
num

[12, 45, 6, 89, 6776, 87, 0.8, 0]

In [50]:
sorted(num)

[0, 0.8, 6, 12, 45, 87, 89, 6776]

In [51]:
?sorted


In [52]:
Student.index("Sw")

ValueError: 'Sw' is not in list

In [53]:
?upper

Object `upper` not found.


In [54]:
room = "Sw Yong"

In [55]:
room_up=room.upper()

In [56]:
print(room_up)

SW YONG


## 包、函数的导入
包的导入：```import 包名```  
函数的导入也可以用 ```from 包名 import 函数名```

In [59]:
import math

In [61]:
math.pi

3.141592653589793

In [1]:
import numpy as np
a=np.array([1,2])

In [2]:
a

array([1, 2])

In [1]:
# 创建棒球运动员的身高列表 baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# 导入numpy包
import numpy as np

# 用列表baseball创建numpy数组：np_baseball
np_baseball = np.array(baseball)

# 打印np_baseball的数据类型
print(type(np_baseball))

# 将以厘米为单位的身高转换成以米为单位，并输出
np_baseball_m = np_baseball / 100
print(np_baseball_m)

# 找出高于2米的运动员身高数据
print(np_baseball_m[np_baseball_m > 2])

# 打印输出最后一个棒球运动员的身高
print(np_baseball_m[-1])

# 打印输出最后两个运动员的身高
print(np_baseball_m[-2:])

<class 'numpy.ndarray'>
[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]
[2.15 2.1  2.1  2.09]
2.0
[2.09 2.  ]


## Numpy二维数组


In [3]:
np_2d = np.array([[1.73,1.65,1.86,1.79],
                [65.4,59.2,88.4,68.4]])
np_2d

array([[ 1.73,  1.65,  1.86,  1.79],
       [65.4 , 59.2 , 88.4 , 68.4 ]])

In [4]:
np_2d.shape

(2, 4)

这是一个2行、5列的二维数组，第一行代表身高，第二行代表体重。索引结构如下图所示：

![](http://localhost:8890/notebooks/Intro_to_Python/array.png)

切片操作

In [14]:
print(np_2d)
print(np_2d[0]) #选取第一行
print(np_2d[0][2])#选取第一行第三列
print(np_2d[0,2])#选取第一行第三列
print(np_2d[:,1:3])#选取每一行的第2、3列
print(np_2d[1,:])#选取第二行的所有列

[[ 1.73  1.65  1.86  1.79]
 [65.4  59.2  88.4  68.4 ]]
[1.73 1.65 1.86 1.79]
1.86
1.86
[[ 1.65  1.86]
 [59.2  88.4 ]]
[65.4 59.2 88.4 68.4]


二维数组的运算

In [15]:
print(np_2d)
np_2d*2

[[ 1.73  1.65  1.86  1.79]
 [65.4  59.2  88.4  68.4 ]]


array([[  3.46,   3.3 ,   3.72,   3.58],
       [130.8 , 118.4 , 176.8 , 136.8 ]])

In [16]:
print(np_2d)
np_2d**2

[[ 1.73  1.65  1.86  1.79]
 [65.4  59.2  88.4  68.4 ]]


array([[2.99290e+00, 2.72250e+00, 3.45960e+00, 3.20410e+00],
       [4.27716e+03, 3.50464e+03, 7.81456e+03, 4.67856e+03]])

In [17]:
print(np_2d)
np_2d+np_2d

[[ 1.73  1.65  1.86  1.79]
 [65.4  59.2  88.4  68.4 ]]


array([[  3.46,   3.3 ,   3.72,   3.58],
       [130.8 , 118.4 , 176.8 , 136.8 ]])

In [18]:
sample = np.array([
       [  74.  ,  215.  ,   34.69],
       [  72.  ,  210.  ,   30.78],
       [  72.  ,  210.  ,   35.43],
       [  73.  ,  188.  ,   35.71],
       [  69.  ,  176.  ,   29.39],
       [  69.  ,  209.  ,   30.77],
       [  71.  ,  200.  ,   35.07],
       [  76.  ,  231.  ,   30.19],
       [  71.  ,  180.  ,   27.05],
       [  73.  ,  188.  ,   23.88],
       [  73.  ,  180.  ,   26.96],
       [  74.  ,  185.  ,   23.29],
       [  74.  ,  160.  ,   26.11],
       [  69.  ,  180.  ,   27.55],
       [  70.  ,  185.  ,   34.27],
       [  73.  ,  189.  ,   27.99],
       [  75.  ,  185.  ,   22.38],
       [  78.  ,  219.  ,   22.89],
       [  79.  ,  230.  ,   25.76],
       [  76.  ,  205.  ,   36.33]])

In [19]:
height = sample[:,1]

In [20]:
height

array([215., 210., 210., 188., 176., 209., 200., 231., 180., 188., 180.,
       185., 160., 180., 185., 189., 185., 219., 230., 205.])

In [22]:
np.mean(height)#计算平均身高

196.25

In [23]:
np.median(height)#计算中位数

188.5

In [24]:
np.std(height)#计算标准差

18.616860637604827

In [25]:
np.corrcoef(sample[:,0], sample[:,1])#使用 np.corrcoef() 函数计算体重和身高的相关系数：

array([[1.        , 0.50671793],
       [0.50671793, 1.        ]])

In [30]:
help (corrcoefr)

NameError: name 'corrcoefr' is not defined

In [31]:
data = np.round(np.random.normal(1.75, 0.20, size=100), 2)#使用 Numpy 还可以进行统计模拟，生成随机数或符合特定分布的数值。比如，下面的代码生成了一组100个符合正态分布的数值，均值是1.75，标准差是0.2。

In [32]:
data

array([2.19, 1.71, 1.63, 1.65, 1.51, 1.85, 1.95, 2.21, 1.62, 2.06, 1.9 ,
       1.91, 1.76, 1.85, 1.69, 1.81, 1.79, 1.78, 1.8 , 1.77, 1.87, 2.01,
       1.57, 1.73, 1.73, 1.7 , 1.63, 1.41, 1.9 , 1.81, 2.13, 1.71, 1.78,
       1.64, 1.65, 2.05, 1.68, 1.72, 1.79, 1.64, 1.85, 1.97, 1.5 , 1.65,
       1.85, 1.86, 1.93, 1.79, 1.92, 2.01, 1.47, 1.94, 2.05, 1.79, 1.97,
       1.72, 1.9 , 1.58, 1.84, 1.65, 1.91, 1.87, 1.97, 1.81, 1.74, 1.63,
       2.02, 1.73, 1.85, 1.42, 1.7 , 1.58, 1.88, 1.59, 1.6 , 1.69, 1.87,
       1.25, 1.63, 1.9 , 1.83, 1.76, 1.82, 2.04, 1.86, 1.72, 1.78, 2.06,
       1.58, 1.56, 1.7 , 1.7 , 1.84, 1.54, 2.  , 1.9 , 1.39, 1.38, 1.46,
       1.31])

In [33]:
sum(height)#python中计算

3925.0

In [34]:
np.sum(height)#numpy中计算

3925.0

像 sum()、sort()这类的函数，Numpy 和 Python 中都有，那么它们的区别在哪里呢？关键在于 Numpy 中的计算速度更快，因为 Numpy 是专门针对数值计算的，而 Python 还要考虑其他数据类型。

In [35]:
# 创建足球运动员的位置和对应的身高数据
positions = ['GK', 'M', 'A', 'D', 'M', 'D', 'M', 'M', 'M', 'A', 'M', 'M', 'A', 'A', 'A', 'M', 'D', 'A', 'D', 'M', 'GK', 'D', 'D', 'M', 'M', 'M', 'M', 'D', 'M', 'GK']
heights = [191, 184, 185, 180, 181, 187, 170, 179, 183, 186, 185, 170, 187, 183, 173, 188, 183, 180, 188, 175, 193, 180, 185, 170, 183, 173, 185, 185, 168, 190]

# 导入numpy包
import numpy as np

# 将列表 positions 和 heights 分别转化成numpy数组: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# 将守门员的身高数据存入变量 gk_heights， 守门员对应的位置编码是’GK‘
gk_heights = np_heights[np_positions == 'GK']

# 将守门员之外的其他运动员的身高数据存入变量 other_heights
other_heights = np_heights[np_positions != 'GK']

# 打印输出守门员身高的中位数，替换代码中的'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# 打印输出其他运动员身高的中位数，替换代码中的'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 183.0
