标准安装的Python中用列表(list)保存一组值， 可以用来当作数组使用， 不过由于列
表的元素可以是任何对象， 因此列表中所保存的是对象的指针。 这样为了保存一个
简单的[1,2,3]， 需要有3个指针和三个整数对象。 对于数值运算来说这种结构显然比
较浪费内存和CPU计算时间。  
此外Python还提供了一个array模块， array对象和列表不同， 它直接保存数值， 和C
语言的一维数组比较类似。 但是由于它不支持多维， 也没有各种运算函数， 因此也
不适合做数值运算。  
NumPy的诞生弥补了这些不足， NumPy提供了两种基本的对象：ndarray（Ndimensional array object） 和 ufunc（universal function object） 。 ndarray(下文统
一称之为数组)是存储单一数据类型的多维数组， 而ufunc则是能够对数组进行处理
的函数

In [2]:
#推荐以下方式导入NumPy函数库
import numpy as np

我们可以通过给array函数传递Python的序列对象创建数组， 如果传递的是多层嵌套
的序列， 将创建多维数组(下例中的变量c):

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array((5, 6, 7, 8))
c = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
b

array([5, 6, 7, 8])

In [4]:
c

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [5]:
c.dtype

dtype('int32')

数组的大小可以通过其shape属性获得

In [6]:
a.shape

(4,)

In [7]:
c.shape

(3, 4)

In [10]:
c.shape=2,6 #改变数组的形式

In [9]:
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

使用数组的reshape方法， 可以创建一个改变了尺寸的新数组， 原数组的shape保持
不变

In [11]:
d = a.reshape((2,2))

In [12]:
d

array([[1, 2],
       [3, 4]])

数组a和d其实共享数据存储内存区域， 因此修改其中任意一个数组的元素都会同时
修改另外一个数组的内容：

In [14]:
a[1] = 100 # 将数组a的第一个元素改为100
d # 注意数组d中的2也被改变了

array([[  1, 100],
       [  3,   4]])

- arange函数类似于python的range函数， 通过指定开始值、 终值和步长来创建
一维数组， 注意数组不包括终值:

In [17]:
np.arange(0,20,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

- linspace函数通过指定开始值、 终值和元素个数来创建一维数组， 可以通过
endpoint关键字指定是否包括终值， 缺省设置是包括终值:

In [21]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

- logspace函数和linspace类似， 不过它创建等比数列， 下面的例子产生1(10^0)
到100(10^2)、 有20个元素的等比数列

In [29]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])