In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b

array([5, 6, 7, 8])

In [5]:
c

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [6]:
print(len(a))


4

In [41]:
print(a[0].dtype)#dtype 函数可以获得数组元素的数据类型
print(a.dtype)
arr_f = np.array([1.23,3.44,32.3])
print(arr_f.dtype)

int32
int32
float64


In [8]:
a.shape

(4,)

In [9]:
c.shape


(3, 4)

In [21]:
c.shape = 6,2 #arr.shape x,y 可将数组重组为x*y型的数组

In [22]:
c

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10]])

In [30]:
d = c.reshape((2,6))#reshape函数运行后 c、d数组共享内存

In [34]:
d[0][0]=880

In [35]:
d


array([[880,   2,   3,   4,   4,   5],
       [  6,   7,   7,   8,   9,  10]])

In [36]:
c

array([[880,   2],
       [  3,   4],
       [  4,   5],
       [  6,   7],
       [  7,   8],
       [  9,  10]])